platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: '3.5.3-jdk-8'

inputs:
  - name: apps-movie-fun-code
  - name: version

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |

    cd apps-movie-fun-code
    mvn versions:set -DnewVersion=$(cat ../version/number)
    mvn clean package -DskipTests -Dmaven.test.skip=true
    cp target/moviefun-*.war ../build-output
